# Generated by Django 4.1 on 2022-08-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_category_link_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='author',
        ),
    ]
