# Generated by Django 3.2 on 2023-08-14 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0003_link_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Tag',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RenameField(
            model_name='link',
            old_name='category',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='link',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='votes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['title', 'url', 'tag'], name='main_idxs'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['description'], name='sub_idxs'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='name_index'),
        ),
        migrations.AddField(
            model_name='linkcomment',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.link'),
        ),
    ]
