# Generated by Django 4.1 on 2022-08-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_remove_link_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='link',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='link',
            name='title',
        ),
    ]
